name: Pete Graham Software Developer
description: Yes I love technology
meta_description: "Writings about programmning and software development"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 10
baseurl: /
domain_name: 'http://petegraham.co.uk'
google_analytics: 'UA-1161798-1'
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://petegraham.co.uk'
author:         'Pete Graham'
authorTwitter:  'petexgraham'

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

collections:
    work:
        output: true
        permalink:  /work/:title/

gems:
    - jekyll-redirect-from
